### ISSUE TITLE
Issue : No Documentation and Installation guide.

### ISSUE THREAD

**Issue by Sahil-Chhoker** [BTANISHA11/ExpenseTracker#1]
No description/documentation is present related to project along with absence of installation guide.

**Comment by BTANISHA11** [comment]
> No description/documentation is present related to project along with absence of installation guide.
okk start working on the issue

**Comment by Sahil-Chhoker** [comment]
I need some info about this project from you, like its purpose, why did you come up with this idea, how to install it properly, how to use it and so on...
Please provide with the necessary info.

**Comment by BTANISHA11** [comment]
I am updating everything
