### ISSUE TITLE
Issue: Backend not working properly

### ISSUE THREAD

**Issue by jiveshkalra** [BTANISHA11/ExpenseTracker#10]
Whenever we try to add some transaction , there is error that is poping up in the console 

![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/1b7abe0e-0359-471a-b4d5-77240e422e64)
![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/591b10ba-f9d0-40d6-9e13-cb7011bb3831)

**Comment by BTANISHA11** [comment]
start working on it.

**Comment by jiveshkalra** [comment]
Please assign me this issue
