### ISSUE TITLE
UI Enhancements : Missing Title and Favicon

### ISSUE THREAD

**Issue by jiveshkalra** [BTANISHA11/ExpenseTracker#11]
The site does not have any title or Favicons or any such description
![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/0cfb69de-b2fb-4495-ae9e-e073b02b5e46)

**Comment by BTANISHA11** [comment]
start working

**Comment by jiveshkalra** [comment]
please assign me this issue
