### ISSUE TITLE
Develop Navbar for the website

### ISSUE THREAD

**Issue by BTANISHA11** [BTANISHA11/ExpenseTracker#12]

**Comment by adarsh-site** [comment]
please assign this issue to me.

**Comment by ritwikdurga** [comment]
Hello mam, Can i be assigned this issue please?

**Comment by adarsh-site** [comment]
> Hello mam, Can i be assigned this issue please?

bro I am already working on it.

**Comment by ritwikdurga** [comment]
> > Hello mam, Can i be assigned this issue please?
> 
> bro I am already working on it.

I think multiple people can be assigned

**Comment by saimohan11** [comment]
Mam, please assign this to me I will use tailwind framework and develop good navbar.

**Comment by BTANISHA11** [comment]
the issue is already assigned .It will be assigned to others only when the first one assigned the issue is not working on it.

**Comment by adarsh-site** [comment]
@BTANISHA11 Unfortunately, due to unforeseen circumstances, I won't be able to continue working on this issue. So, please assign it to someone else.
