### ISSUE TITLE
UI Enhancements : The date and time field needs improvement

### ISSUE THREAD

**Issue by adarsh-site** [BTANISHA11/ExpenseTracker#14]
<img width="406" alt="image" src="https://github.com/BTANISHA11/ExpenseTracker/assets/120160355/486ffafd-3e9d-440a-9e25-17e39d217769">

**Comment by jiveshkalra** [comment]
hey , isnt that the same issue that i originally created like 8 hours ago?
Ref : [Issue Number 9 ]( https://github.com/BTANISHA11/ExpenseTracker/issues/9 )

**Comment by adarsh-site** [comment]
> hey , isnt that the same issue that i originally created like 8 hours ago? Ref : [Issue Number 9 ](https://github.com/BTANISHA11/ExpenseTracker/issues/9)

not exactly. you were specific to time format but i planned to improve it in some different way
