### ISSUE TITLE
two "package.json" files present

### ISSUE THREAD

**Issue by achyu-dev** [BTANISHA11/ExpenseTracker#2]
I noticed the presence of two ```package.json``` files. One outside ```expense-tracker``` folder and one more outside it. 
One more request - please avoid committing ```node_modules```

Thank you

**Comment by BTANISHA11** [comment]
> I noticed the presence of two `package.json` files. One outside `expense-tracker` folder and one more outside it. One more request - please avoid committing `node_modules`
> 
> Thank you

ok start working on the issue.
