### ISSUE TITLE
Changes in the Project File Structure

### ISSUE THREAD

**Issue by jiveshkalra** [BTANISHA11/ExpenseTracker#3]
The project structure is a bit messy , It can be made a lot better by removing the node modules folder and adding all the files to a single place instead of the folder "expense-tracker"
and this project structure makes it hard to refer to the documentation as well

here is what can be done
- [ ] Removal of node modules folder as it takes extra space and can be downloaded easily with the `npm install` command 
- [ ] Moving all files from the "expense-tracker" folder to the outside folder and removing the extra package.json and package-lock.json 
- [ ] Editing the documentation to adhere to the new file structure , adding a new `npm install` command.

**Comment by BTANISHA11** [comment]
> The project structure is a bit messy , It can be made a lot better by removing the node modules folder and adding all the files to a single place instead of the folder "expense-tracker" and this project structure makes it hard to refer to the documentation as well
> 
> here is what can be done
> 
> * [ ]  Removal of node modules folder as it takes extra space and can be downloaded easily with the `npm install` command
> * [ ]  Moving all files from the "expense-tracker" folder to the outside folder and removing the extra package.json and package-lock.json
> * [ ]  Editing the documentation to adhere to the new file structure , adding a new `npm install` command.

start working on the issue.

**Comment by jiveshkalra** [comment]
Can you please assign this task to me?

**Comment by BTANISHA11** [comment]
> Can you please assign this task to me?

okk start working on it

**Comment by BTANISHA11** [comment]
only make changes in readme file folder structure was improved already for everyone
