### ISSUE TITLE
Issue: Vercel Link Provided is not working 

### ISSUE THREAD

**Issue by jiveshkalra** [BTANISHA11/ExpenseTracker#4]
The [Vercel App Link](https://expense-tracker-two-lake.vercel.app/) provided is not functioning and giving a 404 Not Found Error

![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/50c9067e-53c6-4a0f-8ad6-7658f565a2a3)

**Comment by BTANISHA11** [comment]
yes that is a bug in website that needs to be solved.

**Comment by jiveshkalra** [comment]
Shall I do it ? can you assign it to me?
