### ISSUE TITLE
UI Enhancements : The Time is not fully visible in the input

### ISSUE THREAD

**Issue by jiveshkalra** [BTANISHA11/ExpenseTracker#9]
In the input section , the UI doesnt show the entire time , it cuts on half , 

![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/8bec825c-da4b-4f5f-8eef-56845d201171)

![image](https://github.com/BTANISHA11/ExpenseTracker/assets/127482713/71138d8e-77f7-4b08-9077-56e3bc24c7cc)

**Comment by BTANISHA11** [comment]
Ok start working in the issue
